[package]
name = "pg-embed"
version = "0.2.0"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/faokunega/pg-embed"
documentation = "https://docs.rs/pg-embed"
description = "Run a Postgresql database locally on Linux, MacOS or Windows as part of another Rust application or test."
edition = "2018"
keywords = [ "database", "postgres", "postgresql", "embedded", "server" ]
categories = [ "database", "database-implementations", "development-tools", "asynchronous" ]
authors = ["Franz-Aliu Okunega <aokunega@gmail.com>"]

[dependencies]
reqwest = "0.11.2"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
thiserror = "1.0"
archiver-rs = "0.5"