combine_control_expr = false
control_brace_style = "ClosingNextLine"
fn_single_line = true
force_multiline_blocks = true
format_strings = true
max_width = 40
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 20
use_field_init_shorthand = true
wrap_comments = true